// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using beetobee.catalog.api.Data;

#nullable disable

namespace beetobee.catalog.api.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260325212730_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("beetobee.catalog.api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            AvailableQuantity = 50,
                            Category = "Electronics",
                            Description = "Industry-leading noise cancelling wireless headphones.",
                            Name = "Sony WH-1000XM5 Headphones",
                            Price = 349.99m,
                            SKU = "ELEC-001"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000002"),
                            AvailableQuantity = 20,
                            Category = "Electronics",
                            Description = "4K Smart TV with Quantum HDR and Alexa built-in.",
                            Name = "Samsung 65\" QLED TV",
                            Price = 1299.99m,
                            SKU = "ELEC-002"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000003"),
                            AvailableQuantity = 100,
                            Category = "Clothing",
                            Description = "Men's running shoes with Air cushioning.",
                            Name = "Nike Air Max 270",
                            Price = 129.99m,
                            SKU = "CLTH-001"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000004"),
                            AvailableQuantity = 75,
                            Category = "Clothing",
                            Description = "Classic straight fit jeans in dark wash.",
                            Name = "Levi's 501 Original Jeans",
                            Price = 69.99m,
                            SKU = "CLTH-002"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000005"),
                            AvailableQuantity = 60,
                            Category = "Home",
                            Description = "Electric pressure cooker with 7 cooking functions.",
                            Name = "Instant Pot Duo 7-in-1",
                            Price = 89.99m,
                            SKU = "HOME-001"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000006"),
                            AvailableQuantity = 30,
                            Category = "Home",
                            Description = "Cordless vacuum with laser dust detection.",
                            Name = "Dyson V15 Detect Vacuum",
                            Price = 749.99m,
                            SKU = "HOME-002"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000007"),
                            AvailableQuantity = 200,
                            Category = "Books",
                            Description = "A handbook of agile software craftsmanship.",
                            Name = "Clean Code by Robert C. Martin",
                            Price = 34.99m,
                            SKU = "BOOK-001"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000008"),
                            AvailableQuantity = 15,
                            Category = "Toys",
                            Description = "1:8 scale model with 3599 pieces.",
                            Name = "LEGO Technic Bugatti Chiron",
                            Price = 449.99m,
                            SKU = "TOYS-001"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000009"),
                            AvailableQuantity = 80,
                            Category = "Sports",
                            Description = "High-performance running shoes with BOOST midsole.",
                            Name = "Adidas Ultraboost 22 Running Shoes",
                            Price = 189.99m,
                            SKU = "SPRT-001"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000010"),
                            AvailableQuantity = 25,
                            Category = "Home",
                            Description = "Professional-grade blender for smoothies and soups.",
                            Name = "Vitamix 5200 Blender",
                            Price = 549.99m,
                            SKU = "HOME-003"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
