// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using beetobee.order.infrastructure;

#nullable disable

namespace beetobee.order.infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326155347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("beetobee.order.domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerReference")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerReference = new Guid("c0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerReference = new Guid("c0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerReference = new Guid("c0000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("beetobee.order.domain.Models.Order", b =>
                {
                    b.OwnsMany("beetobee.order.domain.Models.OrderItem", "OrderItems", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("OrderId", "ProductId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.HasData(
                                new
                                {
                                    OrderId = new Guid("b0000000-0000-0000-0000-000000000001"),
                                    ProductId = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                                    Quantity = 1
                                },
                                new
                                {
                                    OrderId = new Guid("b0000000-0000-0000-0000-000000000001"),
                                    ProductId = new Guid("a1b2c3d4-0001-0000-0000-000000000003"),
                                    Quantity = 2
                                },
                                new
                                {
                                    OrderId = new Guid("b0000000-0000-0000-0000-000000000002"),
                                    ProductId = new Guid("a1b2c3d4-0001-0000-0000-000000000005"),
                                    Quantity = 1
                                },
                                new
                                {
                                    OrderId = new Guid("b0000000-0000-0000-0000-000000000002"),
                                    ProductId = new Guid("a1b2c3d4-0001-0000-0000-000000000007"),
                                    Quantity = 3
                                },
                                new
                                {
                                    OrderId = new Guid("b0000000-0000-0000-0000-000000000003"),
                                    ProductId = new Guid("a1b2c3d4-0001-0000-0000-000000000002"),
                                    Quantity = 1
                                },
                                new
                                {
                                    OrderId = new Guid("b0000000-0000-0000-0000-000000000003"),
                                    ProductId = new Guid("a1b2c3d4-0001-0000-0000-000000000009"),
                                    Quantity = 1
                                });
                        });

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
